### ISSUE TITLE
Path to "vendor" folder should not be hardcoded

### ISSUE THREAD

**Issue by sascha-egerer** [helhum/typo3-crontab#1]
https://github.com/helhum/typo3-crontab/blob/c54125a0432601147ad2eaa9fd6132c6a329b505/Classes/ProcessManager.php#L118
As the name of the "vendor" folder can be changed by configuration it should not be hardcoded.
Maybe the calling command can be used to determine the path to the binary.
Like this
https://github.com/FlowdDe/scheduler-forker/blob/d7f332cb69cdd87735ece8b29a78625788c1a079/Classes/Command/SchedulerCommand.php#L48-L51

**Comment by sascha-egerer** [comment]
Ok, just saw that the method is also called via a module controller. It won't work this way then for sure... 
But there should be some kind of configuration to define how the command is executed.

**Comment by helhum** [comment]
Thanks. I know. The `runIsolated` method is currently only used to trigger the execution via web UI. The cron command itself is not affected.

Since I currently rather tend to completely remove the possibility to directly trigger execution of tasks via the UI and only allow adding it to the queue for execution, this issue will go away along with the code :)

**Comment by helhum** [comment]
> It won't work this way then for sure...

Yes, it currently only works if the vendor directory is `vendor`.

**Comment by sascha-egerer** [comment]
👍 Then feel free to close the issue or maybe just keep it until the code is gone to prevent somebody complaining about that again :)

**Comment by helhum** [comment]
I will keep the ticket open for now, as it marks one to do item.

**Comment by helhum** [comment]
Fixed :)

**Comment by sascha-egerer** [comment]
Love you! 😂
